import requests
import csv
import json

# Define base URL and endpoint
base_url = 'https://restcountries.com/v3.1'
endpoint = '/lang/{lang}'

# Sample lang codes
lang_codes = [
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Avaric",
    "Aymara",
    "Azerbaijani",
    "Bambara",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Chamorro",
    "Chechen",
    "Chichewa",
    "Chinese",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi",
    "Dutch",
    "Dzongkha",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Fula",
    "Galician",
    "Georgian",
    "German",
    "Greek",
    "Guaraní",
    "Gujarati",
    "Haitian",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Interlingua",
    "Indonesian",
    "Interlingue",
    "Irish",
    "Igbo",
    "Inupiaq",
    "Ido",
    "Icelandic",
    "Italian",
    "Inuktitut",
    "Japanese",
    "Javanese",
    "Kalaallisut",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Kikuyu",
    "Kinyarwanda",
    "Kirghiz",
    "Komi",
    "Kongo",
    "Korean",
    "Kurdish",
    "Kwanyama",
    "Latin",
    "Luxembourgish",
    "Ganda",
    "Limburgish",
    "Lingala",
    "Lao",
    "Lithuanian",
    "Luba-Katanga",
    "Latvian",
    "Manx",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Māori",
    "Marathi",
    "Marshallese",
    "Mongolian",
    "Nauru",
    "Navajo",
    "Ndebele",
    "Ndonga",
    "Nepali",
    "Norwegian",
    "Norwegian Bokmål",
    "Norwegian Nynorsk",
    "Nuosu",
    "Nyanja",
    "Occitan",
    "Ojibwe",
    "Oriya",
    "Oromo",
    "Ossetian",
    "Pāli",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Romansh",
    "Kirundi",
    "Russian",
    "Sanskrit",
    "Sardinian",
    "Sindhi",
    "Northern Sami",
    "Samoan",
    "Sango",
    "Serbian",
    "Scottish Gaelic",
    "Shona",
    "Sinhala",
    "Slovak",
    "Slovene",
    "Somali",
    "Southern Sotho",
    "Spanish",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tamil",
    "Telugu",
    "Tajik",
    "Thai",
    "Tigrinya",
    "Tibetan",
    "Turkmen",
    "Tagalog",
    "Tswana",
    "Tonga",
    "Turkish",
    "Tsonga",
    "Tatar",
    "Twi",
    "Tahitian",
    "Uighur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volapük",
    "Walloon",
    "Wolof",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang",
    "Zulu"
]

# Function to send request and handle response
def get_country_info(lang_code):
    url = f'{base_url}{endpoint}'.format(lang=lang_code)
    response = requests.get(url)
    if (response.status_code == 200 or response.status_code == 404):
        return response.json(), response.status_code
    else:
        return {'status': response.status_code, 'message': response.reason}

# Main function
def main():
    # Open CSV file for writing
    with open('country_info_lang.csv', 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['testCaseId', 'queryParameters', 'operationId', 'path', 'httpMethod', 'headerParameters', 
                      'pathParameters', 'formParameters', 'bodyParameter', 'statusCode', 'responseBody']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()

        # Loop through country names
        for i, lang_code in enumerate(lang_codes):
            country_info, status = get_country_info(lang_code)
            print("API Call " + str(i) + "\nStatus Code " + str(status))
            response_body = json.dumps(country_info)
            writer.writerow({
                'testCaseId': i,
                'queryParameters': '',
                'operationId': 'v3Lang',
                'path': '/lang/{lang}',
                'httpMethod': 'GET',
                'headerParameters': '',
                'pathParameters': f'lang={lang_code}',
                'formParameters': '',
                'bodyParameter': '',
                'statusCode': status,
                'responseBody': response_body
            })

if __name__ == '__main__':
    main()
    
